app = "your-app-name"
primary_region = "ams"

[env]
API_ID = "123456"
API_HASH = "your_api_hash"

[[services]]
internal_port = 8080
protocol = "tcp"

  [[services.ports]]
  port = 80
  handlers = ["http"]
