services:
  - type: worker
    name: telegram-video-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: API_ID
        value: "123456"            # عدل هذا بقيمة api_id
      - key: API_HASH
        value: "your_api_hash"     # عدل هذا بقيمة api_hash
