services:
  - type: worker
    name: telegram-video-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_ID
        value: your_api_id
      - key: API_HASH
        value: your_api_hash
      - key: PHONE_NUMBER
        value: +your_phone_number
